### ISSUE TITLE
KeyError from `object[type_id]`

### ISSUE THREAD

**Issue by danielsamuels** [Galile0/pyrope#7]
I'm testing all of the replays currently uploaded to Rocket League Replays against this library and reporting any issues I fine.

This error was generated from parsing the following replay: https://www.rocketleaguereplays.com/replays/10322/

```
Traceback (most recent call last):
  File "/var/www/rocket-league-replays-heatmaps/main.py", line 38, in <module>
    replay.parse_netstream()
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/replay.py", line 51, in parse_netstream
    raise e
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/replay.py", line 45, in parse_netstream
    self.netstream = self._parse_frames(qout, ev)
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/replay.py", line 224, in _parse_frames
    frame.parse_frame(self._netstream_raw, self.objects, propertymapper)
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/frame.py", line 23, in parse_frame
    self.actors = self._parse_actors(netstream, objects, propertymapper)
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/frame.py", line 51, in _parse_actors
    type_name, data = self._parse_new_actor(netstream, objects)
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/frame.py", line 95, in _parse_new_actor
    type_name = objects[type_id]
KeyError: 38929069
```

**Comment by Galile0** [comment]
That's a somewhat broken replay? I'm honestly not to sure. When viewing ingame, I can clearly see two players on each side. Yakuza leaves at some point in the match leaving Shadowsk1ll alone. But in the header I can't find a hint that shadowsk1ll was even present in the game. This leads to a point where it just breaks when reading the PartyLeader property. Probably something got mixed up when Yakuza left the match and something ingame just got confused as to who is Partyleader. I'm pretty sure that this just causes an offset when reading the bits. Nothing that can't be fixed, but will need some try and Error. For now it has to remain a broken replay file (As far as parsers go, ingame it shows fine ~.~)

**Comment by Galile0** [comment]
Ok, this was easier than expected: If it reads a wonky uid, it just rolls back the bitposition and continues as normal. In these cases, partyLeader will have (-1, -1, -1) as values. The result seems to be fine, no errors, no weird parsings. It doesn't change the fact that the replay is at least somewhat broken. The header data does not represent the actual replay data. Good thing: All players are getting parsed correctly from the netstream datas, and with pyrain, all heatmaps got generated as expected (Even for players who are not noted in the replay header)
