### ISSUE TITLE
KeyError: 'Engine.PlayerReplicationInfo:bIsSpectator'

### ISSUE THREAD

**Issue by danielsamuels** [Galile0/pyrope#9]
I'm testing all of the replays currently uploaded to Rocket League Replays against this library and reporting any issues I find.

This error was generated from parsing: https://www.rocketleaguereplays.com/replays/14093/

```
Traceback (most recent call last):
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/netstream_property_parsing.py", line 121, in read_property_value
    value = parsing[property_name](bitstream)
KeyError: 'Engine.PlayerReplicationInfo:bIsSpectator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/rocket-league-replays-heatmaps/main.py", line 38, in <module>
    replay.parse_netstream()
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/replay.py", line 51, in parse_netstream
    raise e
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/replay.py", line 45, in parse_netstream
    self.netstream = self._parse_frames(qout, ev)
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/replay.py", line 224, in _parse_frames
    frame.parse_frame(self._netstream_raw, self.objects, propertymapper)
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/frame.py", line 23, in parse_frame
    self.actors = self._parse_actors(netstream, objects, propertymapper)
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/frame.py", line 62, in _parse_actors
    raise e
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/frame.py", line 57, in _parse_actors
    objects, propertymapper)
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/frame.py", line 87, in _parse_existing_actor
    raise e
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/frame.py", line 84, in _parse_existing_actor
    property_value = read_property_value(property_name, netstream)
  File "/var/www/rocket-league-replays-heatmaps/.venv/lib/python3.4/site-packages/pyrope/netstream_property_parsing.py", line 124, in read_property_value
    % (property_name, bitstream.read('hex:64')))
pyrope.exceptions.PropertyParsingError: ('Dont know how to parse bits for Engine.PlayerReplicationInfo:bIsSpectator Have some raw Bits: ee1584f0385b8fc0', {'Props_till_err': {}}, {'CurrFrameActors': OrderedDict([('110e_Car_Default', {'actor_id': 110, 'startpos': 3396846, 'data': {'TAGame.RBActor_TA:ReplicatedRBState': {'rot': (0.9928891872920926, 0.500015259254738, -0.999603259376812), 'vec1': (-256, -2, -185), 'vec2': (9, -3, 0), 'flag': False, 'pos': (-256, 3840, 19)}}, 'new': False, 'actor_type': 'Archetypes.Car.Car_Default'}), ('111e_Car_Default', {'actor_id': 111, 'startpos': 3397007, 'data': {'TAGame.RBActor_TA:ReplicatedRBState': {'rot': (0.9928891872920926, 0.500015259254738, -0.999603259376812), 'vec1': (-256, -2, -185), 'vec2': (9, -3, 0), 'flag': False, 'pos': (0, 4608, 19)}}, 'new': False, 'actor_type': 'Archetypes.Car.Car_Default'}), ('112e_Ball_Default', {'actor_id': 112, 'startpos': 3397171, 'data': {'TAGame.RBActor_TA:ReplicatedRBState': {'rot': (-1.000030518509476, -1.000030518509476, -1.000030518509476), 'vec1': (0, 0, -189), 'vec2': (0, 0, 0), 'flag': False, 'pos': (-256, -256, -157)}}, 'new': False, 'actor_type': 'Archetypes.Ball.Ball_Default'}), ('85e_Car_Default', {'actor_id': 85, 'startpos': 3397311, 'data': {'TAGame.RBActor_TA:ReplicatedRBState': {'rot': (0.9928891872920926, -0.500015259254738, -0.999603259376812), 'vec1': (-256, -254, -185), 'vec2': (-9, 3, 0), 'flag': False, 'pos': (256, -3840, 19)}}, 'new': False, 'actor_type': 'Archetypes.Car.Car_Default'})])}, {'ErrorActorId': 178, 'ErrorActorType': 'TAGame.Default__PRI_TA'})
```

**Comment by Galile0** [comment]
Already closed in: 1a8e115a38d5652e7d3eac6ac4aea7df6ad8a977
